# Generated by Django 4.2.7 on 2024-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_helpsupport_mission_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
