# Generated by Django 4.2.7 on 2024-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_testimonial_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsupport',
            options={'ordering': ['order'], 'verbose_name': 'Help & Support Item', 'verbose_name_plural': 'Help & Support Items'},
        ),
        migrations.AddField(
            model_name='helpsupport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help_support/'),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='icon',
            field=models.CharField(help_text="Font Awesome class name (e.g., 'fa-heart')", max_length=50),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
