# Generated by Django 4.2.7 on 2024-11-27 04:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_helpsupport_options_helpsupport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file (max 100MB)', null=True, upload_to='reason_videos/'),
        ),
        migrations.AddField(
            model_name='reason',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube or Vimeo video URL', null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reason',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reasons/'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
